import type { Metadata } from "next";
import { getHomePageData } from "@/lib/api";
import { Noto_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/bloggr.svg",
  },
};

interface HomePageData {
  isLoggedIn: boolean;
  user: {
    username: string;
    email: string;
    firstName: string;
    lastName: string;
    avatarURL?: string;
    bio?: string;
    fullName: string;
    role: string;
  } | null;
}

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data: HomePageData | null = await getHomePageData();

  const navbarData: HomePageData = data || {
    isLoggedIn: false,
    user: null,
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSans.className} antialiased bg-gray-50 dark:bg-[#121212]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="md:px-10 px-5 py-6 sticky top-0 z-50">
            <Navbar user={navbarData.user} isLoggedIn={navbarData.isLoggedIn} />
          </header>{" "}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
