import type { Metadata } from "next";
import { handleLoggedInUserData } from "@/lib/api";
import { Noto_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/bloggr.svg",
  },
};

interface LoggedInUserData {
  isLoggedIn: boolean;
  user: {
    username: string;
    email: string;
    firstName: string;
    lastName: string;
    avatarURL?: string;
    bio?: string;
    fullName: string;
    role: string;
  } | null;
}

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data: LoggedInUserData | null = await handleLoggedInUserData();

  const navbarData: LoggedInUserData = data || {
    isLoggedIn: false,
    user: null,
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSans.className} antialiased  dark:bg-[#121212]`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="md:px-10 px-5 py-5 sticky top-0 z-50 backdrop-blur-sm ">
            <Navbar user={navbarData.user} isLoggedIn={navbarData.isLoggedIn} />
          </header>{" "}
          <Theme accentColor="gray">{children}</Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
