export const blogTags: string[] = [
  "Technology",
  "Software Development",
  "Web Development",
  "Frontend",
  "Backend",
  "Full-Stack",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "API",
  "Database",
  "MongoDB",
  "SQL",
  "Serverless",
  "Cloud Computing",
  "AWS",
  "DevOps",
  "CI/CD",
  "Docker",
  "Kubernetes",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Blockchain",
  "Web3",
  "Gaming",
  "Gadgets",
  "UI/UX",
  "mechanical keyboards",
  "switches",
  "gaming peripherals",
  "productivity tools",
  "custom keyboards",
  "keycaps",
  "ergonomics",
  "technology reviews",

  "Business",
  "Startup",
  "Entrepreneurship",
  "Marketing",
  "SEO",
  "Content Marketing",
  "Social Media",
  "Productivity",
  "Leadership",
  "Career Development",
  "Finance",
  "Investing",
  "Cryptocurrency",
  "Personal Finance",
  "Real Estate",
  "Economics",

  "Lifestyle",
  "Health",
  "Wellness",
  "Fitness",
  "Nutrition",
  "Mental Health",
  "Mindfulness",
  "Meditation",
  "Yoga",
  "Self-Improvement",
  "Personal Growth",
  "Relationships",
  "Parenting",
  "Home & Garden",
  "Minimalism",
  "Sustainability",

  "Travel",
  "Adventure",
  "Backpacking",
  "Digital Nomad",
  "City Guide",
  "Travel Tips",
  "Culture",
  "History",
  "Food & Drink",
  "Cuisine",
  "Recipes",
  "Wine",
  "Coffee",
  "Japan",
  "Europe",
  "Asia",

  "Art",
  "Design",
  "Graphic Design",
  "Photography",
  "Filmmaking",
  "Music",
  "Writing",
  "Blogging",
  "Books",
  "Reading",
  "DIY",
  "Crafts",
  "Fashion",
  "Movies",
  "TV Shows",
  "Hobby",

  "Science",
  "Space",
  "Astronomy",
  "Physics",
  "Biology",
  "Environment",

  "Nature",
  "Hiking",
  "Outdoors",
  "Wildlife",

  "News",
  "Politics",
  "Education",
  "Learning",
  "Tutorial",
  "How-To",
  "Opinion",
  "Review",
  "Storytelling",
  "Inspiration",
  "Productivity Hacks",
];
